[versions]
bstats = "3.1.0"
adventure = "4.25.0"
packetevents = "2.11.0"

[libraries]
platform-paper = { module = "io.papermc.paper:paper-api", version = "1.21.10-R0.1-SNAPSHOT" }

adventure = { module = "net.kyori:adventure-api", version.ref = "adventure" }
adventure-text-minimessage = { module = "net.kyori:adventure-text-minimessage", version.ref = "adventure" }
bstats-bukkit = { module = "org.bstats:bstats-bukkit", version.ref = "bstats" }
bstats-sponge = { module = "org.bstats:bstats-sponge", version.ref = "bstats" }
dazzleconf = { module = "space.arim.dazzleconf:dazzleconf-toml", version = "2.0.0-M1" }
luckperms = { module = "net.luckperms:api", version = "5.5" }
slf4j = { module = "org.slf4j:slf4j-api", version = "2.0.16" }
packetevents-api = { module = "com.github.retrooper:packetevents-api", version.ref = "packetevents" }
packetevents-spigot = { module = "com.github.retrooper:packetevents-spigot", version.ref = "packetevents" }
packetevents-sponge = { module = "com.github.retrooper:packetevents-sponge", version.ref = "packetevents" }
snakeyaml = { module = "org.yaml:snakeyaml", version = "2.3" }

[plugins]
sponge = { id = "org.spongepowered.gradle.plugin", version = "2.2.0" }
resourceFactory-paper = { id = "xyz.jpenilla.resource-factory-paper-convention", version = "1.2.0" }
run-paper = { id = "xyz.jpenilla.run-paper", version = "2.3.1" }